var lastbench = ['kalam', 'balam', 'salam'];
lastbench.push('jalal');
lastbench.push('john');
lastbench.push('jalam');
//console.log(lastbench);

//add an element into array
var friendsAge = [19, 14, 44,];
friendsAge.push(40);
console.log(friendsAge);

//remove an element from array
var friendsAge = [19, 14, 44];
friendsAge.pop(44);
friendsAge.pop();
var addedAge = friendsAge.push(44, 50, 60);
console.log(friendsAge);
console.log(addedAge);


